name: miranime
description: A Flutter app to explore anime using the Jikan API.
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

flutter:
  uses-material-design: true
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/product_sans_bold.ttf
        - asset: assets/fonts/product_sans_italic.ttf
        - asset: assets/fonts/product_sans_regular.ttf
  assets:
    - assets/icons/

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  go_router: ^13.0.0
  flutter_staggered_animations: ^1.0.0

  carousel_slider:
    git:
      url: https://github.com/sampaio96/flutter_carousel_slider.git
      ref: master

  provider: ^6.1.1
  animated_text_kit: ^4.2.2
  marquee: ^2.2.3
  url_launcher: ^6.2.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"
  adaptive_icon_background: "assets/icons/background.png"